Repository WSUCEG-7140/Team-Alpha, pull requests merged in 2023-07, with the labels that each got.

#26 Issue#4: Adding Test Cases
  .github/workflows/python_tests.yml
  img/forkme.png
  img/json-forms.png
  index.html
  lib/bootstrap-select/css/bootstrap-select.min.css
  lib/bootstrap-select/js/bootstrap-select.min.js
  lib/bootstrap-select/js/i18n/defaults-en_US.min.js
  lib/bootstrap/css/bootstrap-theme.css.map
  lib/bootstrap/css/bootstrap-theme.min.css
  lib/bootstrap/css/bootstrap.css.map
  lib/bootstrap/css/bootstrap.min.css
  lib/bootstrap/fonts/glyphicons-halflings-regular.eot
  lib/bootstrap/fonts/glyphicons-halflings-regular.svg
  lib/bootstrap/fonts/glyphicons-halflings-regular.ttf
  lib/bootstrap/fonts/glyphicons-halflings-regular.woff
  lib/bootstrap/fonts/glyphicons-halflings-regular.woff2
  lib/bootstrap/js/bootstrap.min.js
  lib/codemirror/codemirror-javascript.js
  lib/codemirror/codemirror.css
  lib/codemirror/codemirror.js
  lib/jquery-1.11.3.min.js
  lib/markdown.min.js
  lib/octicons/README.md
  lib/octicons/octicons-local.ttf
  lib/octicons/octicons.css
  lib/octicons/octicons.eot
  lib/octicons/octicons.less
  lib/octicons/octicons.scss
  lib/octicons/octicons.svg
  lib/octicons/octicons.ttf
  lib/octicons/octicons.woff
  lib/octicons/sprockets-octicons.scss
  tests/final_tests.py
  tests/test_main.py
Labels: enhancement

#27 Issue#4: Updating Source Branch
  .github/workflows/python_tests.yml
  tests/test_main.py
Labels: bug

#18 Issue#17: Display default values in an array when initial data is passed.
  src/js/brutusin-json-forms.js
Labels: bug

#22 Issue#8: Add new field to support password type
  src/js/brutusin-json-forms.js
Labels: enhancement

#16 Issue#15: Validation to fail if required field is empty.
  src/js/brutusin-json-forms.js
Labels: bug

#14 Issue#10: Add new field to support email and its validation
  src/js/brutusin-json-forms.js
Labels: enhancement

#20 Issue#19: Support Custom-Class Support
  src/js/brutusin-json-forms.js
Labels: bug

#21 Issue#7: Make changes to string element to be empty rather than null.
  src/js/brutusin-json-forms.js
Labels: bug

#25 Issue#24: Adding new field to support radio button
  index.html
  src/css/brutusin-json-forms.css
  src/js/brutusin-json-forms-bootstrap.js
  src/js/brutusin-json-forms.js
Labels: enhancement

#36 Issue#35: Adding Functionalities to work for radio buttons.
  src/js/brutusin-json-forms-bootstrap.js
  src/js/brutusin-json-forms.js
Labels: bug

#39 Issue#37: Add new field to support URL type.
  src/js/brutusin-json-forms.js
Labels: enhancement

#34 Issue#13: Adding new fields to support date and time and add new schema
  index.html
Labels: enhancement

#30 Issue#11: Clean data after onChange between oneOf
  src/js/brutusin-json-forms.js
Labels: bug

#29 Issue#9: Remove eval function
  src/js/brutusin-json-forms.js
Labels: enhancement

#40 Issue#38: Add new field to support checkboxes in a field.
  index.html
  src/css/brutusin-json-forms.css
  src/js/brutusin-json-forms.js
Labels: enhancement

#31 Issue#6: Remove Colon from Title in Html forms.
  index.html
  src/js/brutusin-json-forms-bootstrap.js
  src/js/brutusin-json-forms.js
Labels: enhancement

#33 Issue#32: getData() function to get working with oneOf schema
  src/js/brutusin-json-forms.js
Labels: bug

#62 Issue#55: Abstract usage of glyphicon as bootstrap 4 doesn't support it.
  index.html
  src/css/brutusin-json-forms.css
  src/js/brutusin-json-forms-bootstrap.js
Labels: bug

#46 Issue#44: Fix data support for checkbox which is retrieving empty values
  src/js/brutusin-json-forms.js
Labels: bug

#49 Issue#48: Add new schema for URL Changes.
  index.html
Labels: bug

#58 Issue#41: Add new field to support phone number.
  index.html
  src/js/brutusin-json-forms.js
Labels: enhancement

#59 Issue#51: Add new field to support range input type.
  index.html
  src/css/brutusin-json-forms.css
  src/js/brutusin-json-forms-bootstrap.js
  src/js/brutusin-json-forms.js
Labels: enhancement

#61 Issue#54: Add Collapsible form changes as a new schema.
  index.html
Labels: enhancement

#60 Issue#53: Add new schema to create registration form.
  index.html
Labels: enhancement

#63 Issue#42: Add more test cases to additional functional UI changes.
  tests/final_tests.py
  tests/test_main.py
Labels: enhancement

#76 Issue#66:Beautify the form to loosen the fields with bootstrap 4 .
  src/js/brutusin-json-forms.js
Labels: enhancement

#74 Issue#69: Add new schema for Product Listing Form
  index.html
Labels: enhancement

#73 Issue#43: Add a reset button in final page to update all fields to Null
  index.html
  src/js/brutusin-json-forms.js
Labels: enhancement

#75 Issue#68: Add new field to support file format type
  index.html
  src/js/brutusin-json-forms-bootstrap.js
Labels: enhancement

#78 Issue#67: Add new schema for Delivery Form
  index.html
  src/css/brutusin-json-forms.css
Labels: enhancement

#79 Issue#70: Update Validation Error Popup with bootstrap 4 update.
  src/css/brutusin-json-forms.css
  src/js/brutusin-json-forms-bootstrap.js
Labels: enhancement

#80 Issue#65:Add new schema for Contact Form.
  index.html
Labels: enhancement

#82 Issue#81: Add final test cases for added changes in sprint 3
  index.html
  tests/final_tests.py
  tests/test_main.py
Labels: enhancement

#83 Committing Code Coverage changes.
  .github/workflows/python_tests.yml
Labels: enhancement

#86 Issue#72: Renaming Documentation
  .github/workflows/python_tests.yml
  Doxyfile
  Doxygen_Documentation.zip
  README.md
Labels: documentation

#84 Issue#71: Adding Minutes Meetings.
  meeting_minutes_1.md
  meeting_minutes_2.md
  meeting_minutes_3.md
  meeting_minutes_4.md
  meeting_minutes_5.md
  meeting_minutes_6.md
Labels: enhancement

#89 Issue#72: Adding description for running test cases.
  src/js/brutusin-json-forms-bootstrap.js
  src/js/brutusin-json-forms.js
  tests/final_tests.py
  tests/test_main.py
Labels: documentation
